import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GameSocketContextProvider } from "@/providers/GameSocketContext";
import { ClientInitializer } from "@/providers/ClientInitializer";
import { CubeProvider } from "@/providers/CubeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientInitializer />
        <CubeProvider>
          <GameSocketContextProvider>{children}</GameSocketContextProvider>
        </CubeProvider>
      </body>
    </html>
  );
}
