import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GameSocketContextProvider } from "@/providers/GameSocketContext";
import { ClientInitializer } from "@/providers/ClientInitializer";
import { CubeProvider } from "@/providers/CubeContext";

const bitbeat = localFont({
  src: "../../public/fonts/DnfBitbeatV2.otf",
  variable: "--font-bitbeat",
  weight: "600",
});
const neodgm = localFont({
  src: "../../public/fonts/NeoDungeunmoPro.ttf",
  variable: "--font-neodgm",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bitbeat.variable} ${neodgm.variable} antialiased`}>
        <ClientInitializer />
        <CubeProvider>
          <GameSocketContextProvider>{children}</GameSocketContextProvider>
        </CubeProvider>
      </body>
    </html>
  );
}
