import type { Metadata } from "next";
import "./globals.css";
import { GameSocketContextProvider } from "@/providers/GameSocketContext";
import { ClientInitializer } from "@/providers/ClientInitializer";
import { CubeProvider } from "@/providers/CubeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientInitializer />
        <CubeProvider>
          <GameSocketContextProvider>{children}</GameSocketContextProvider>
        </CubeProvider>
      </body>
    </html>
  );
}
